### ISSUE TITLE
bug in strategy/functions.md

### ISSUE THREAD

**Issue by nirno** [blankly-finance/blankly-docs#27]
--- content/en/strategy/functions.md.orig
+++ content/en/strategy/functions.md
@@ -170,7 +170,7 @@
 
 a = blankly.Alpaca()
 s = Strategy(a)
-s.add_price_event(some_bar_event, 'MSFT', resolution='15m', init=init)
+s.add_bar_event(some_bar_event, 'MSFT', resolution='15m', init=init)
 ```
 
 ### `time() -> float`

**Comment by EmersonDove** [comment]
Sorry can you elaborate a bit more

**Comment by nirno** [comment]
This is the last line of the "Example Use Case" for the `add_bar_event` function after its documentation: the example should use `add_bar_event` to add `some_bar_event` to strategy, but it says `add_price_event` instead of `add_bar_event`.

**Comment by EmersonDove** [comment]
Should be fixed thanks!
